version: "2"
checks:
  argument-count:
    enabled: false
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 40
  method-count:
    config:
      threshold: 25

plugins:
  # https://docs.codeclimate.com/docs/eslint
  # ES Linting requires an .eslintrc file to tweak checks.
  eslint:
    enabled: true
  markdownlint:
    enabled: false
  # CSS is generated and shouldn't be linted.
  csslint:
    enabled: false
  # We don't lint our coffee. Eew.
  coffeelint:
    enabled: false
  # SASS Lint requires a .sass-lint.yml file in the repo in order to tweak settings.
  # Withouth the .sass-lint.yml file it will run with the defaults.
  # Defaults file: https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml
  sass-lint:
    enabled: true
  # SCSS Lint requires a .scss-lint.yml file in the repo in order to tweak settings.
  # Withouth the .scss-lint.yml file it will run with the defaults.
  # Defaults file: https://github.com/brigade/scss-lint/blob/master/config/default.yml
  scss-lint:
    enabled: false
  phpcodesniffer:
    enabled: true
    checks:
      Drupal Commenting FunctionComment TypeHintMissing:
        enabled: true
      Drupal Commenting FunctionComment IncorrectTypeHint:
        enabled: true
      DrupalPractice Commenting CommentEmptyLine SpacingAfter:
        enabled: true
      Drupal NamingConventions ValidFunctionName ScopeNotCamelCaps:
        enabled: true
      Drupal NamingConventions ValidClassName StartWithCaptial:
        enabled: false
      Drupal NamingConventions ValidFunctionName NotCamelCaps:
        enabled: false
      DrupalPractice General ClassName ClassPrefix:
        enabled: false
      Drupal NamingConventions ValidClassName NoUnderscores:
        enabled: true
    config:
      file_extensions: "php,inc,install,module,profile"
      standard: "Drupal,DrupalPractice"
  phpmd:
    enabled: true
    checks:
      Design/WeightedMethodCount:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      UnusedFormalParameter:
        enabled: false
      Naming/ShortVariable:
        enabled: false
    config:
      # https://phpmd.org/rules/index.html
      # The following sets include everything except the controversial set.
      # We can configure these further through .xml files. See docs.
      rulesets: "cleancode,codesize,design,naming,unusedcode"
      # Include special Drupal file extensions.
      file_extensions: "inc,module,profile,php,install"
  # https://docs.codeclimate.com/docs/phan
  phan:
    enabled: true
    config:
      file_extensions: "php,module,profile,inc"
      # minimum-severity: 1
      ignore-undeclared: true
      # quick: true
      # backward-compatiility-checks: true
      # dead-code-detection: true
  # https://docs.codeclimate.com/docs/duplication
  duplication:
    enabled: true
    # exclude_paths:
    #   - examples/
    config:
      languages:
        javascript:
          mass_threshold: 50
          # count_threshold: 3
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - TODO
        - todo
        - dpm
        - dsm
# exclude these files/paths
exclude_patterns:
- "test"
- "tests"
- "**/tests/**/*"
- "vendor"
- "vendors"
- "node_modules"
- "composer.json"
- "package.json"
- "webpack.config.js"
- "**.min.*"
- "spec/"
- "dist/"
